### ISSUE TITLE
Problems not using yarn

### ISSUE THREAD

**Issue by throrin19** [sudokar/nx-serverless#853]
When we try to add new workspace to the project, and don't have yarn installed (we don't use it with my team), we have this error : 

```
/bin/sh: yarn: command not found
node:internal/errors:841
  const err = new Error(message);
              ^

Error: Command failed: yarn --version
/bin/sh: yarn: command not found

    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at getPackageManagerVersion (/Users/User/test/nx-serverless-main/node_modules/nx/src/utils/package-manager.js:98:41)
    at Object.yarn (/Users/User/test/nx-serverless-main/node_modules/nx/src/utils/package-manager.js:40:33)
    at getPackageManagerCommand (/Users/User/test/nx-serverless-main/node_modules/nx/src/utils/package-manager.js:89:36)
    at compileToolsDir (/Users/User/test/nx-serverless-main/node_modules/nx/src/command-line/workspace-generators.js:72:64)
    at compileTools (/Users/User/test/nx-serverless-main/node_modules/nx/src/command-line/workspace-generators.js:53:5)
    at Object.<anonymous> (/Users/User/test/nx-serverless-main/node_modules/nx/src/command-line/workspace-generators.js:26:24)
    at Generator.next (<anonymous>) {
  status: 127,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(33) [Uint8Array] [
       47,  98, 105, 110,  47, 115, 104,  58,
       32, 121,  97, 114, 110,  58,  32,  99,
      111, 109, 109,  97, 110, 100,  32, 110,
      111, 116,  32, 102, 111, 117, 110, 100,
       10
    ]
  ],
  pid: 66866,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(33) [Uint8Array] [
     47,  98, 105, 110,  47, 115, 104,  58,
     32, 121,  97, 114, 110,  58,  32,  99,
    111, 109, 109,  97, 110, 100,  32, 110,
    111, 116,  32, 102, 111, 117, 110, 100,
     10
  ]
}
```

**Comment by sudokar** [comment]
Hi @throrin19,

Thanks for your message, I will look into it and let you know

**Comment by sudokar** [comment]
@throrin19  May I know the commands used to replicate this use and fix it, please

**Comment by throrin19** [comment]
@sudokar I don't remember, it was many months ago. I think it was with the add of workspace : 

```
nx g serverless my-stack
```

**Comment by sudokar** [comment]
> 

Thanks, I will check on that

**Comment by sudokar** [comment]
> @sudokar I don't remember, it was many months ago. I think it was with the add of workspace :
> 
> ```
> nx g serverless my-stack
> ```

Thanks, I will check on that
